package com.echo8.aoc2020;

import org.apache.commons.lang3.StringUtils;

import java.util.*;

public class Day6Part2 {
    private static final String INPUT = "elmcifawqgkp\n" +
            "dynwslejfcrkpv\n" +
            "\n" +
            "pagrovuzscemqiy\n" +
            "paxomsgyuvc\n" +
            "\n" +
            "hcoljgiraqvs\n" +
            "hgrvxqcojal\n" +
            "arjhqclogv\n" +
            "jlrvackhogq\n" +
            "\n" +
            "bagctysnmhodfe\n" +
            "tfchsdoeagmnby\n" +
            "csdhnotbfgayme\n" +
            "\n" +
            "rksnmhbxi\n" +
            "dyhavkcjrp\n" +
            "\n" +
            "t\n" +
            "tx\n" +
            "t\n" +
            "\n" +
            "fd\n" +
            "of\n" +
            "wejznfa\n" +
            "f\n" +
            "fs\n" +
            "\n" +
            "lmz\n" +
            "ml\n" +
            "lm\n" +
            "\n" +
            "zsidpewbu\n" +
            "uziwpbsed\n" +
            "dpzwbuise\n" +
            "uiebdpswz\n" +
            "dsuwzeibp\n" +
            "\n" +
            "lpsk\n" +
            "srgk\n" +
            "\n" +
            "xdktfapvyqmsgnzl\n" +
            "nmgqvxjzdlayrspf\n" +
            "\n" +
            "reydlgxzvsokpi\n" +
            "sexvyokldpgr\n" +
            "yrqnkuixselvod\n" +
            "rylcshwxtefbadmokjv\n" +
            "\n" +
            "qhxfn\n" +
            "hqfx\n" +
            "xifhq\n" +
            "fqhx\n" +
            "\n" +
            "oqvjyepsdlmagcixutb\n" +
            "ebxgoqytzujdpvcma\n" +
            "nxrjofuytqpwdahkcgbv\n" +
            "\n" +
            "gfwnlcbvuk\n" +
            "kqfnoucvgibw\n" +
            "pfsthrgmavun\n" +
            "\n" +
            "aiejncxrvbwfgqyulz\n" +
            "vlzgrnxqfuacybweis\n" +
            "cvkqrezlxbiagyuwfsn\n" +
            "\n" +
            "j\n" +
            "j\n" +
            "j\n" +
            "j\n" +
            "\n" +
            "oxumbipdk\n" +
            "kmuoxditbp\n" +
            "bkpxmqioud\n" +
            "\n" +
            "tsfjaiqdwexbonpvr\n" +
            "peuisyawojtxbr\n" +
            "utewromzksapjixb\n" +
            "klbrwmeahxistpgjco\n" +
            "\n" +
            "izepslcjydnrxm\n" +
            "afedhyzbsmvlirtjncx\n" +
            "\n" +
            "mbsuxzjkwaoclgr\n" +
            "sjcmlribkwgazx\n" +
            "zbwmxgcstearjlk\n" +
            "klcabsjxzgwrm\n" +
            "\n" +
            "cuiexkrvhj\n" +
            "okijtbmqdu\n" +
            "znafslk\n" +
            "\n" +
            "eyqvtziobjcgsp\n" +
            "mqjezigkycobpnsvw\n" +
            "\n" +
            "wmhza\n" +
            "wazsh\n" +
            "fazhw\n" +
            "\n" +
            "yqcwloght\n" +
            "wygdqmot\n" +
            "tgdybsoufwpq\n" +
            "rwjoqyagtbe\n" +
            "\n" +
            "sdmjqln\n" +
            "mjqdibcleksw\n" +
            "oqsldmj\n" +
            "fxjpsmdlvatq\n" +
            "fdslomzuqj\n" +
            "\n" +
            "zlfm\n" +
            "zfmnl\n" +
            "ufzlqm\n" +
            "\n" +
            "oahgbpdmqwriuxzcyksfj\n" +
            "kcszyjxptoduhfrbmgawqi\n" +
            "hjkwbpogufscqzryxamid\n" +
            "ghkjxpozqsauycwimrbdf\n" +
            "rqywuxbgokjfzacihmsdp\n" +
            "\n" +
            "otysqx\n" +
            "xsfyotq\n" +
            "tsxqyo\n" +
            "\n" +
            "z\n" +
            "ua\n" +
            "vz\n" +
            "s\n" +
            "\n" +
            "w\n" +
            "j\n" +
            "\n" +
            "drn\n" +
            "pbetfc\n" +
            "lna\n" +
            "\n" +
            "lfg\n" +
            "hvsinjd\n" +
            "\n" +
            "jr\n" +
            "orj\n" +
            "jr\n" +
            "\n" +
            "huarfp\n" +
            "forhwguxp\n" +
            "uhiprf\n" +
            "fhrupn\n" +
            "hrfup\n" +
            "\n" +
            "zbndtlwehxku\n" +
            "uqbtwnxymkl\n" +
            "\n" +
            "dfzbqrtenscjplvkaumwx\n" +
            "wtbeclnmkzsqyfajdpuvrx\n" +
            "\n" +
            "uxmjrbdnhfoqgys\n" +
            "ymgjdosanq\n" +
            "dnjqwcsgoyem\n" +
            "oqdengmsyja\n" +
            "jynsmdtqgoe\n" +
            "\n" +
            "odhjyxwncrt\n" +
            "ndehcmjwxytrio\n" +
            "cjydnrowxht\n" +
            "\n" +
            "bgijpxv\n" +
            "qbnvmxguj\n" +
            "xqjgmuvzb\n" +
            "\n" +
            "gcs\n" +
            "ep\n" +
            "\n" +
            "idpzuvjseoqnck\n" +
            "mwdfyiacpklbjnheuorvszgx\n" +
            "\n" +
            "fozderigtmcsjk\n" +
            "mubhxldvez\n" +
            "\n" +
            "cobw\n" +
            "wobc\n" +
            "bwoc\n" +
            "baowmcr\n" +
            "\n" +
            "mbka\n" +
            "w\n" +
            "\n" +
            "izpceoqsglfv\n" +
            "zsqglfvecoi\n" +
            "\n" +
            "eufkyohpwq\n" +
            "pyqhfeuok\n" +
            "noyqfpeukrh\n" +
            "\n" +
            "zwjkfayco\n" +
            "lhcwf\n" +
            "hclrwf\n" +
            "fwnbtc\n" +
            "\n" +
            "hfym\n" +
            "hfym\n" +
            "hyfm\n" +
            "myhf\n" +
            "yhmf\n" +
            "\n" +
            "jbntrwuqkv\n" +
            "utxjiayq\n" +
            "thcqupxjdl\n" +
            "\n" +
            "voxr\n" +
            "ogvxr\n" +
            "rvox\n" +
            "\n" +
            "ukltspqnmirezyxj\n" +
            "ubxmpteqynocizjr\n" +
            "dzjfykwsxivumtreqpn\n" +
            "\n" +
            "edyhapqtzcowf\n" +
            "isdawoqgzytfpech\n" +
            "wafdnqrzoelycmhtp\n" +
            "hatufwpdqcyoez\n" +
            "\n" +
            "qolmhyg\n" +
            "hblygmo\n" +
            "yogmlh\n" +
            "\n" +
            "bqoym\n" +
            "yqnoebm\n" +
            "byqom\n" +
            "\n" +
            "b\n" +
            "b\n" +
            "ir\n" +
            "o\n" +
            "hb\n" +
            "\n" +
            "cgikybplfujswhx\n" +
            "plguhjmkbfwxyic\n" +
            "xwjyhlmkcgubpif\n" +
            "kyiwgcfxhjmplbu\n" +
            "xgpuhvikblfjwcy\n" +
            "\n" +
            "ljgdtkuaqwyvcfpx\n" +
            "cuqnjyvsbrlfai\n" +
            "\n" +
            "gbnodyhuvxr\n" +
            "rpgaqs\n" +
            "zgsfpclr\n" +
            "rgs\n" +
            "\n" +
            "iyqnvafsuzjxcodltghwkp\n" +
            "vihygqjntpldufxscwaokz\n" +
            "iqdhlngzfysaxopvukjcbtw\n" +
            "uldtisoknyzaqjpcgwvhfx\n" +
            "\n" +
            "ztrfwlagshexiob\n" +
            "eafoigstrbzxwhn\n" +
            "gsaoufnbherxilwtz\n" +
            "iabgwxotzerhfs\n" +
            "kxyriswahgtezcdvobf\n" +
            "\n" +
            "hwzsodnb\n" +
            "dzohwsb\n" +
            "zdwhsbno\n" +
            "ondwhxzsb\n" +
            "islzbdwhof\n" +
            "\n" +
            "gcurdsepvakxzymo\n" +
            "wufbtpgqncjakoyems\n" +
            "\n" +
            "hxectqimn\n" +
            "fetxchnkm\n" +
            "ncexth\n" +
            "brytxscnpgejoh\n" +
            "akufcendxht\n" +
            "\n" +
            "qelcfbkwrxthnzoaj\n" +
            "mxkrqzwflijnbctdh\n" +
            "brhglkdmcxqjntfzw\n" +
            "\n" +
            "newydrilgcqptjsfzmkoabh\n" +
            "fidvctrzkmsojnleaxqpywgh\n" +
            "\n" +
            "umbrlcdhagvizfnw\n" +
            "webljuvic\n" +
            "buiyvlcsjwk\n" +
            "\n" +
            "bw\n" +
            "bw\n" +
            "wb\n" +
            "bw\n" +
            "bw\n" +
            "\n" +
            "opuyxbvwdk\n" +
            "bxodywpuvk\n" +
            "pdkyovubxw\n" +
            "\n" +
            "z\n" +
            "q\n" +
            "i\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "swvpmuzdhnroikxg\n" +
            "shgkmwindxvpzoru\n" +
            "pgrmkzvdhonwixsu\n" +
            "knwopgiszrumxhdv\n" +
            "\n" +
            "bjqlainyetm\n" +
            "kajmbqnteil\n" +
            "ajneqbytkplmi\n" +
            "domhaiqselcbtjn\n" +
            "ielqjmbntga\n" +
            "\n" +
            "rlsntciqodgjwxbp\n" +
            "oanxipdc\n" +
            "yxicndfpome\n" +
            "pinvfhdoxcy\n" +
            "pdecixvkmnoy\n" +
            "\n" +
            "rdngeljxkzwyfbhot\n" +
            "tmbxojfgwedrkyzn\n" +
            "rtopjxydkgwnevfzb\n" +
            "drbzofetqjyxwakng\n" +
            "\n" +
            "wd\n" +
            "w\n" +
            "w\n" +
            "w\n" +
            "w\n" +
            "\n" +
            "viseyncokafpwl\n" +
            "qjeygvwpdfbzlkou\n" +
            "ovikflerypw\n" +
            "\n" +
            "sdpxiwage\n" +
            "esfgkuxh\n" +
            "grksexh\n" +
            "\n" +
            "wqv\n" +
            "vq\n" +
            "kvq\n" +
            "qv\n" +
            "qv\n" +
            "\n" +
            "btxyedokhlmpauwgq\n" +
            "gpdxuhvofysqamntez\n" +
            "\n" +
            "fcwymjbnulsp\n" +
            "rhzjvwqde\n" +
            "\n" +
            "rnsgbcdytpfz\n" +
            "spcrtybzgnf\n" +
            "sgncyztrpbf\n" +
            "csbtzfnygpr\n" +
            "\n" +
            "lgioemjbdkf\n" +
            "bmokjilhedf\n" +
            "pblsdrtfeiomkj\n" +
            "iomxekgbjlfnd\n" +
            "mzdfjokbile\n" +
            "\n" +
            "dnua\n" +
            "bsaurnxqc\n" +
            "aun\n" +
            "gayun\n" +
            "\n" +
            "ryjkfxnmvphstw\n" +
            "icgwozqxtkbev\n" +
            "\n" +
            "wprgenuj\n" +
            "xnrgmtej\n" +
            "otjvnzwelgru\n" +
            "zgrjenf\n" +
            "jdbiskyeanrcq\n" +
            "\n" +
            "yag\n" +
            "ryga\n" +
            "yia\n" +
            "ayg\n" +
            "ya\n" +
            "\n" +
            "brfjtowysu\n" +
            "ukyfbtjws\n" +
            "bfwgyustjvk\n" +
            "wfjxbhlpmnusqiacyzt\n" +
            "\n" +
            "ktuqeysb\n" +
            "\n" +
            "ecrjuyp\n" +
            "ycpawejr\n" +
            "ejyzrgvo\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "uyevxojtswflbdknp\n" +
            "tavljczymgnxqpbskd\n" +
            "\n" +
            "tnrjqdaeu\n" +
            "yiowqlpk\n" +
            "\n" +
            "sczbe\n" +
            "czesb\n" +
            "ceszb\n" +
            "zscqgeb\n" +
            "ebzsc\n" +
            "\n" +
            "smyewnxtjoiurbclhf\n" +
            "htoenkbfwxursclmjip\n" +
            "juaflnrhosbmixewtc\n" +
            "wljbrincmsoexhfut\n" +
            "\n" +
            "zklm\n" +
            "xfsmerpvkq\n" +
            "mki\n" +
            "\n" +
            "zomlcxbevyukisjqp\n" +
            "dqhmnkfitjaprce\n" +
            "\n" +
            "azemjicynpbwrhgduqtkloxfs\n" +
            "foheycqpuanskgdztiwlmrbx\n" +
            "pzwamfgdnkbrltsqheocxuyi\n" +
            "\n" +
            "fgisklmbdwuaovcxntzjqypr\n" +
            "wrugpbntmcfljqikdovyxsza\n" +
            "\n" +
            "qwgyu\n" +
            "tzfqbdjpxin\n" +
            "kaq\n" +
            "mqwa\n" +
            "gyqa\n" +
            "\n" +
            "juevoildyfwqrpch\n" +
            "juovpelyqfid\n" +
            "ufgvoyldjeipq\n" +
            "\n" +
            "pt\n" +
            "t\n" +
            "\n" +
            "uiwcpryldjo\n" +
            "htwirdqcpuj\n" +
            "iqstpjrdyouv\n" +
            "ejnbrgzapfikudx\n" +
            "puvrmdjil\n" +
            "\n" +
            "ayunwfjq\n" +
            "fnqwyja\n" +
            "ayjqfwn\n" +
            "wqajnfy\n" +
            "\n" +
            "bho\n" +
            "hb\n" +
            "\n" +
            "xeciotqasmblvghjk\n" +
            "ehoaicd\n" +
            "\n" +
            "aibsmhznrkv\n" +
            "havsbirnkm\n" +
            "mvhriaknsbz\n" +
            "ynjbmshavdcekir\n" +
            "\n" +
            "kd\n" +
            "vcwkdq\n" +
            "kd\n" +
            "kd\n" +
            "\n" +
            "desol\n" +
            "egvspodlzk\n" +
            "redosl\n" +
            "dreslo\n" +
            "\n" +
            "sywvarhcmlztiq\n" +
            "orqyclwmhizxsavgtd\n" +
            "mswlviqcyrtahz\n" +
            "qtmjazvcsirlwnpyh\n" +
            "\n" +
            "fes\n" +
            "kdefns\n" +
            "\n" +
            "poubdzithfq\n" +
            "douvaehxcl\n" +
            "dmohnu\n" +
            "eouhrdck\n" +
            "\n" +
            "ympojnsevrc\n" +
            "corspkimven\n" +
            "pvzmeocnhtasbql\n" +
            "vcpokrxmjnes\n" +
            "nspgvmjocer\n" +
            "\n" +
            "xgqvbohjlzpnymrusfc\n" +
            "xytjzfgpslbkruove\n" +
            "blopxszhgvumywjfr\n" +
            "\n" +
            "nacjwslpxki\n" +
            "sjlmkacgniwyx\n" +
            "kilxgnajwsc\n" +
            "xwagtnckiljs\n" +
            "vlawnchrfbixskjd\n" +
            "\n" +
            "icfqnuwxrhg\n" +
            "vnirqgxcmufbh\n" +
            "ghcrtfyloudix\n" +
            "\n" +
            "jrouy\n" +
            "uyroj\n" +
            "juory\n" +
            "rjyou\n" +
            "kuotryj\n" +
            "\n" +
            "fmnkioscvhtzdljuy\n" +
            "excjkilmywdsgunb\n" +
            "curdqnplmkejiays\n" +
            "\n" +
            "cqwgdpihyoleb\n" +
            "qghlcteoydibp\n" +
            "pqoghecdilyb\n" +
            "rfbgcoqplehyiad\n" +
            "yldceuhqpgibo\n" +
            "\n" +
            "twzxq\n" +
            "qnw\n" +
            "\n" +
            "qcvhwkreoit\n" +
            "tvrqwchiuoke\n" +
            "oqktivrchwe\n" +
            "tqeihorcwvk\n" +
            "ikochwtvreq\n" +
            "\n" +
            "rpwmlio\n" +
            "irqkofu\n" +
            "ieubo\n" +
            "tiopa\n" +
            "dzjscgxvionh\n" +
            "\n" +
            "nzmeaqycg\n" +
            "zefliwdyg\n" +
            "gyzwrde\n" +
            "\n" +
            "clmotbvhr\n" +
            "lmhtcwvigerb\n" +
            "zvufasbhtdymcjlr\n" +
            "cevxbltgrmh\n" +
            "\n" +
            "kjvsgouatqxd\n" +
            "dxyajsgoqrt\n" +
            "tagwxqdjsco\n" +
            "\n" +
            "pu\n" +
            "c\n" +
            "gc\n" +
            "\n" +
            "mckf\n" +
            "kgqmf\n" +
            "fmk\n" +
            "odkmptf\n" +
            "\n" +
            "vkqeigoc\n" +
            "kgqcvoei\n" +
            "gkiveqoc\n" +
            "coveiqgk\n" +
            "cgqoveik\n" +
            "\n" +
            "pelbqxgnsicvut\n" +
            "vqsbngtpuxi\n" +
            "suxcnvbqpgit\n" +
            "wqubitsnghoxmyvp\n" +
            "\n" +
            "xqymo\n" +
            "qmxoy\n" +
            "mxqyo\n" +
            "qoxym\n" +
            "\n" +
            "bpey\n" +
            "ygdstpob\n" +
            "pbkhy\n" +
            "hbczyp\n" +
            "\n" +
            "ebkpjsxvganulfohiqdtw\n" +
            "rlpjnfwdisogkhaqtxb\n" +
            "sdbqngowhlktfaxpij\n" +
            "cfngosajqikxpbtdlhw\n" +
            "\n" +
            "pcno\n" +
            "op\n" +
            "co\n" +
            "o\n" +
            "roikw\n" +
            "\n" +
            "nfogth\n" +
            "ochfdpe\n" +
            "lyarougfbx\n" +
            "sifwzvkqo\n" +
            "\n" +
            "byzwnuk\n" +
            "voeqkzhrw\n" +
            "gwjcaekzvhx\n" +
            "zdimwkvc\n" +
            "\n" +
            "hrqitmcukga\n" +
            "aosdujpcnmtqke\n" +
            "\n" +
            "ux\n" +
            "ux\n" +
            "unx\n" +
            "\n" +
            "vt\n" +
            "svt\n" +
            "\n" +
            "pmulitndqgovfjebw\n" +
            "durbtgwjempxon\n" +
            "xsueoprmgkjnbdwt\n" +
            "\n" +
            "ygzrdsxni\n" +
            "gwszyxriqnd\n" +
            "\n" +
            "powyvtg\n" +
            "wvtpoyg\n" +
            "tovgpyw\n" +
            "\n" +
            "ejnqu\n" +
            "jqne\n" +
            "reojq\n" +
            "\n" +
            "fm\n" +
            "mf\n" +
            "mf\n" +
            "mf\n" +
            "xnfm\n" +
            "\n" +
            "px\n" +
            "px\n" +
            "\n" +
            "zakqlib\n" +
            "xaik\n" +
            "\n" +
            "esgdvwxk\n" +
            "devwgkx\n" +
            "eqgxkwvd\n" +
            "evwxdkg\n" +
            "wdgvekx\n" +
            "\n" +
            "jrv\n" +
            "vjr\n" +
            "jrv\n" +
            "jdrv\n" +
            "vjhr\n" +
            "\n" +
            "wgazdye\n" +
            "ywga\n" +
            "gqway\n" +
            "gwvarhy\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "rofbzixqhlpakgndvj\n" +
            "gxphdvzfnoyuqrjke\n" +
            "fvqpnxgozhjrldk\n" +
            "gqphlxkfcnvtzodjrwi\n" +
            "\n" +
            "uzyoinm\n" +
            "zyma\n" +
            "zynmixs\n" +
            "kndmruyz\n" +
            "fhmzqlyw\n" +
            "\n" +
            "fl\n" +
            "fnl\n" +
            "fl\n" +
            "\n" +
            "jgk\n" +
            "kjg\n" +
            "ljgk\n" +
            "\n" +
            "orizljkcpeg\n" +
            "gpcirj\n" +
            "iebcdrj\n" +
            "crjaxfuiqtnv\n" +
            "\n" +
            "hbxktsgyavoufm\n" +
            "xvskgyhutf\n" +
            "sthgzkvfxuyp\n" +
            "ktsguxyfhv\n" +
            "\n" +
            "gxrtjozic\n" +
            "oznjtrxgi\n" +
            "irgztqxkj\n" +
            "gxztrji\n" +
            "irtgvuxzjwysh\n" +
            "\n" +
            "rbskyeqldponazjucmxigh\n" +
            "qnecyzbgaorskjixmvhdl\n" +
            "nhrjoqcsyliwemakxbdtgz\n" +
            "\n" +
            "gpyoakd\n" +
            "ydokpqsba\n" +
            "xudavkfpormnjz\n" +
            "eqkpoda\n" +
            "ciqpogdkba\n" +
            "\n" +
            "ntsgzkpfi\n" +
            "buckqrmpxozevijwlgn\n" +
            "\n" +
            "o\n" +
            "i\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "jhkdypm\n" +
            "pdn\n" +
            "pefzcv\n" +
            "agsbpuxoqrw\n" +
            "lpf\n" +
            "\n" +
            "w\n" +
            "xw\n" +
            "\n" +
            "xqsflmuzdpcrnhjgtwbvie\n" +
            "mxtcnpglidzqhbrjsufvew\n" +
            "amtbqulhdgirpwxvszjcnfe\n" +
            "\n" +
            "evdrpj\n" +
            "tevpmrj\n" +
            "yiwheupjozvsgrklc\n" +
            "epfqbrvaj\n" +
            "ejpnqrv\n" +
            "\n" +
            "lezukstv\n" +
            "sxvdcueapkb\n" +
            "ewujkrnvsz\n" +
            "\n" +
            "s\n" +
            "li\n" +
            "s\n" +
            "xs\n" +
            "\n" +
            "zmornlsckyb\n" +
            "mwblyhercogzsnkd\n" +
            "mbknzyrocsl\n" +
            "\n" +
            "xfpbhqnejgazmvdwtuio\n" +
            "qohwtpidbfjmeguanxv\n" +
            "davwopnqfceltjisgumhrb\n" +
            "beqjmuhivfntgpdawo\n" +
            "dtuvpehyiqbgmjonwfa\n" +
            "\n" +
            "fevqjnuhgsy\n" +
            "chlkrxgbs\n" +
            "\n" +
            "bzevx\n" +
            "k\n" +
            "cif\n" +
            "k\n" +
            "r\n" +
            "\n" +
            "tls\n" +
            "lnty\n" +
            "lt\n" +
            "ltcs\n" +
            "otlf\n" +
            "\n" +
            "yxhftspr\n" +
            "xsfhytrp\n" +
            "xpsrythfqw\n" +
            "srptfxyhu\n" +
            "prtsxyfh\n" +
            "\n" +
            "zanmupcyirdx\n" +
            "yfqpubdamrcknhx\n" +
            "eradnwlxpuvysmj\n" +
            "\n" +
            "p\n" +
            "pb\n" +
            "hp\n" +
            "\n" +
            "hy\n" +
            "hy\n" +
            "yh\n" +
            "ymh\n" +
            "hy\n" +
            "\n" +
            "usocgzpjkfvqniltrxdbhw\n" +
            "yogvrkjxlpnamszudqtwb\n" +
            "\n" +
            "exulnmgbfcjzk\n" +
            "fcexjudknzbl\n" +
            "\n" +
            "ynmtqjve\n" +
            "jveynmq\n" +
            "jnqmvey\n" +
            "eyqnjmv\n" +
            "qnjymve\n" +
            "\n" +
            "ziclnydugfqjretwhv\n" +
            "hljtrbqnwuvcyedfi\n" +
            "lxfyqcvrnhsjiuwtzed\n" +
            "wnvhfditlyrcusqej\n" +
            "\n" +
            "kpaieqjdflocy\n" +
            "ciqpdoklyjaef\n" +
            "qpceifoljakyd\n" +
            "edkfliaqjpocy\n" +
            "kqjoylicpeadf\n" +
            "\n" +
            "sd\n" +
            "shdo\n" +
            "igskvq\n" +
            "\n" +
            "htwfobiycmpdxnzlrujk\n" +
            "uwzrcfxtnmbpyohlidj\n" +
            "zvqwdcoipfxmerusbajlhnyt\n" +
            "\n" +
            "hzwv\n" +
            "whyv\n" +
            "hwvz\n" +
            "bvhlrwuj\n" +
            "\n" +
            "u\n" +
            "tf\n" +
            "sbrc\n" +
            "y\n" +
            "\n" +
            "slbfguyrjqhx\n" +
            "rygfqlsuhx\n" +
            "ygxsqhrluf\n" +
            "\n" +
            "xsrjiu\n" +
            "uweprjg\n" +
            "pjru\n" +
            "yjhmcfunvrqk\n" +
            "irjuw\n" +
            "\n" +
            "zdrjswcaik\n" +
            "tcikawjuzvdxrn\n" +
            "zcrihjwakd\n" +
            "radzyickjw\n" +
            "wadjkecizr\n" +
            "\n" +
            "kvdeitchowuyxljqmabr\n" +
            "klqymaidcxojvwhuebrt\n" +
            "cmurhebtxwkoavqiyjdl\n" +
            "wvabixhqeoydktmrujcl\n" +
            "ajemidblvtycqhkrwxuo\n" +
            "\n" +
            "ufhiespvlbrcqygjakz\n" +
            "cfsphiegkvzjaqyrblu\n" +
            "iaruqfsepgylkzcbjhv\n" +
            "bgfpashzvljqkuicyer\n" +
            "\n" +
            "vjrmlnwzohcyfdxuatqgbpkie\n" +
            "bnqdyilruvescagwkxmthfojzp\n" +
            "xufzhqwciplbronmjtdavkyeg\n" +
            "whmrckbzdgfauqlyjeiotpxvn\n" +
            "\n" +
            "i\n" +
            "ik\n" +
            "i\n" +
            "\n" +
            "omtzex\n" +
            "yiwu\n" +
            "rhmnkgtj\n" +
            "\n" +
            "yu\n" +
            "yu\n" +
            "yu\n" +
            "ucy\n" +
            "yu\n" +
            "\n" +
            "lfbtyapow\n" +
            "ly\n" +
            "cvly\n" +
            "\n" +
            "mxyphzlcgdjobawi\n" +
            "dzkcsjltapygoqufh\n" +
            "\n" +
            "tycelnwdrvoubimhk\n" +
            "mdbivklcetyrwunoh\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "v\n" +
            "x\n" +
            "v\n" +
            "zv\n" +
            "\n" +
            "cjavufbmswohnldpgrkt\n" +
            "phbmwjtofsgxckul\n" +
            "lyuhgmfjoswpxbctk\n" +
            "wlokhucbgsmejztfp\n" +
            "\n" +
            "ovuitnkzey\n" +
            "gxhapflrb\n" +
            "\n" +
            "qzd\n" +
            "zdjq\n" +
            "\n" +
            "dqnbfjustlizexkgymr\n" +
            "gfrziynmkdtsjeql\n" +
            "tfayqdlrsizkngemj\n" +
            "tfyrnesizmgqjlkd\n" +
            "lgadikzmernwfsjtqy\n" +
            "\n" +
            "reklgsoxbfwmqanvu\n" +
            "uolmkbanfyqgxpsrwv\n" +
            "khoswagrvxfqblmtnu\n" +
            "udlngfvmkqoxyrwbas\n" +
            "\n" +
            "gzjqcoa\n" +
            "qt\n" +
            "bdtqlp\n" +
            "\n" +
            "ih\n" +
            "hyi\n" +
            "hi\n" +
            "hif\n" +
            "\n" +
            "yhisc\n" +
            "htxsaujicm\n" +
            "ishc\n" +
            "klhcies\n" +
            "\n" +
            "gimjckpobfq\n" +
            "qogcmipbf\n" +
            "\n" +
            "diqbsenjz\n" +
            "yakmchngwfpj\n" +
            "qxoernzdjvli\n" +
            "\n" +
            "rlnbsqgfx\n" +
            "qsfnxlreb\n" +
            "fxlsgbqnrt\n" +
            "fszxqdgltnbre\n" +
            "qrbcxlpasfn\n" +
            "\n" +
            "kczwo\n" +
            "ckdwoz\n" +
            "kqocuwz\n" +
            "wozckd\n" +
            "\n" +
            "nlqgxw\n" +
            "xgnlqw\n" +
            "wqxngl\n" +
            "qwnxlg\n" +
            "\n" +
            "rwxhuogzcjpfev\n" +
            "pixrgosatwhcbfzvj\n" +
            "hgvoyqwfpzxcnrj\n" +
            "pjrzhfqcgwxov\n" +
            "\n" +
            "pvier\n" +
            "mripe\n" +
            "ipvbr\n" +
            "shcjiwoargp\n" +
            "\n" +
            "aigpjvwdmyrlxsohkecut\n" +
            "ylinsgxukmcpwdetrjahv\n" +
            "\n" +
            "ps\n" +
            "q\n" +
            "r\n" +
            "\n" +
            "cm\n" +
            "mc\n" +
            "mc\n" +
            "mc\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "astrzjgc\n" +
            "arsz\n" +
            "szar\n" +
            "rszai\n" +
            "ayrzsl\n" +
            "\n" +
            "gpjaqzvdtouxrmlciyefkb\n" +
            "gowrpcndejqiztuykvfsam\n" +
            "\n" +
            "axbeqi\n" +
            "kexaqbi\n" +
            "xeaqbi\n" +
            "axbeqi\n" +
            "qaeibx\n" +
            "\n" +
            "vazjticxqo\n" +
            "aqtjzvioc\n" +
            "iozcajvt\n" +
            "zcoitajgv\n" +
            "ibjlncovzta\n" +
            "\n" +
            "gaz\n" +
            "g\n" +
            "gef\n" +
            "\n" +
            "xbg\n" +
            "bgx\n" +
            "xbg\n" +
            "bgx\n" +
            "\n" +
            "sm\n" +
            "sm\n" +
            "sm\n" +
            "ksm\n" +
            "\n" +
            "rjmktglu\n" +
            "rjbfuc\n" +
            "juhri\n" +
            "jur\n" +
            "\n" +
            "wxkrupn\n" +
            "ydzxbclvegnptrsu\n" +
            "nurxpa\n" +
            "nruphx\n" +
            "uxmrjnqp\n" +
            "\n" +
            "fibazcjq\n" +
            "iqzabcfj\n" +
            "fqzibjacg\n" +
            "czjfqiba\n" +
            "abczjfiq\n" +
            "\n" +
            "aqehugzcosv\n" +
            "imwnfcjk\n" +
            "dtyrlpxknbic\n" +
            "\n" +
            "m\n" +
            "m\n" +
            "m\n" +
            "m\n" +
            "m\n" +
            "\n" +
            "xwi\n" +
            "xwi\n" +
            "wix\n" +
            "xwi\n" +
            "\n" +
            "ikyrwtsjo\n" +
            "sntyi\n" +
            "tyis\n" +
            "\n" +
            "fjlt\n" +
            "jflt\n" +
            "tlfj\n" +
            "tlfj\n" +
            "ljtf\n" +
            "\n" +
            "upzaxnkvohebcw\n" +
            "meqitclwfsrhkyj\n" +
            "\n" +
            "bhi\n" +
            "bihvd\n" +
            "ewihub\n" +
            "\n" +
            "tzxswligejqkn\n" +
            "pktiwcexzluvnhj\n" +
            "\n" +
            "hkip\n" +
            "chp\n" +
            "g\n" +
            "\n" +
            "ojnqulc\n" +
            "nupjmcleikyb\n" +
            "\n" +
            "izbtdsufmjpewkrlyg\n" +
            "kwrfpusdimlzgebj\n" +
            "ilgcmrhbvkjduwspefqz\n" +
            "\n" +
            "zouqmp\n" +
            "muq\n" +
            "mqu\n" +
            "mutcq\n" +
            "muozqp\n" +
            "\n" +
            "yfncdoza\n" +
            "zdonyfjac\n" +
            "yadcfnzo\n" +
            "agodcyzfn\n" +
            "zndyocfa\n" +
            "\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "fdylvisp\n" +
            "crzytblojaunei\n" +
            "yclgkqtwui\n" +
            "\n" +
            "mo\n" +
            "mz\n" +
            "dnm\n" +
            "\n" +
            "hbd\n" +
            "h\n" +
            "ct\n" +
            "\n" +
            "gloqe\n" +
            "leog\n" +
            "exlo\n" +
            "oe\n" +
            "ejwor\n" +
            "\n" +
            "byznh\n" +
            "rueczpmxo\n" +
            "\n" +
            "rdtnicsag\n" +
            "xswrgiaqucn\n" +
            "gsericaqn\n" +
            "zcauinrwgfs\n" +
            "\n" +
            "zmwekqucjobahgvsypx\n" +
            "okqmveubjwaxthcpygsz\n" +
            "shvofekzxqmaucpdjywbg\n" +
            "qwcefjzmkghsxaybuopv\n" +
            "cpwhsqkanjzlmouvgbxey\n" +
            "\n" +
            "b\n" +
            "b\n" +
            "b\n" +
            "os\n" +
            "b\n" +
            "\n" +
            "fgdkrtovwxmcqau\n" +
            "xlhutvowmgfacp\n" +
            "ysbegzuwnfoacxvt\n" +
            "fmalxitohjcgwvu\n" +
            "\n" +
            "kufdawncqr\n" +
            "ftcnsuraxwbok\n" +
            "qupfncdwkraz\n" +
            "\n" +
            "ujembfoqtlhkxnipz\n" +
            "mqkzehnupijbofxtl\n" +
            "fezkqiolpjmhtuxbn\n" +
            "ukpftihomblnxzjeq\n" +
            "fekoztlbipmnjuqhx\n" +
            "\n" +
            "wuantesoxgzlkdyv\n" +
            "aeonwtksudylxgzv\n" +
            "vxogzenswdtculaky\n" +
            "eadntklvowxsyzgu\n" +
            "ktzeogldvuysxnaw\n" +
            "\n" +
            "t\n" +
            "qt\n" +
            "\n" +
            "hyanftqlru\n" +
            "faqnyurlht\n" +
            "lhtaryfqun\n" +
            "lashwuftqnyrk\n" +
            "\n" +
            "ujekx\n" +
            "aep\n" +
            "\n" +
            "fnhzwlpbktujeqds\n" +
            "nfbzhjeksgqlowxp\n" +
            "\n" +
            "us\n" +
            "jbcao\n" +
            "xkp\n" +
            "mp\n" +
            "zkpl\n" +
            "\n" +
            "baesofy\n" +
            "oyesf\n" +
            "seqyh\n" +
            "stapey\n" +
            "uesy\n" +
            "\n" +
            "vtp\n" +
            "vtp\n" +
            "vpt\n" +
            "pvt\n" +
            "tpv\n" +
            "\n" +
            "fploymws\n" +
            "wyfosmpl\n" +
            "wlopfysm\n" +
            "owmylpsf\n" +
            "\n" +
            "az\n" +
            "za\n" +
            "za\n" +
            "az\n" +
            "az\n" +
            "\n" +
            "wjrv\n" +
            "vjubnr\n" +
            "qdtjvys\n" +
            "jvp\n" +
            "jcuv\n" +
            "\n" +
            "qrhynskzmxlduoftcwg\n" +
            "xwnzchoylfgdrmkqtu\n" +
            "kcmnwfxhqdrylousgzt\n" +
            "qusjzclktfmgwrhdxyon\n" +
            "bxwhmyqzdfoilnutckrg\n" +
            "\n" +
            "aqp\n" +
            "l\n" +
            "z\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "hdlofpgw\n" +
            "wpchuflo\n" +
            "\n" +
            "dxrezotclpb\n" +
            "eplobcxtdzry\n" +
            "rpzxboltcde\n" +
            "deobtupzvcxlr\n" +
            "cvnboptxrlzde\n" +
            "\n" +
            "uja\n" +
            "uja\n" +
            "aujx\n" +
            "\n" +
            "z\n" +
            "gmw\n" +
            "\n" +
            "escljbdgo\n" +
            "tdoyqghj\n" +
            "chdtjugo\n" +
            "ohdjug\n" +
            "pfjwnmrogadvi\n" +
            "\n" +
            "bl\n" +
            "lcb\n" +
            "lb\n" +
            "klb\n" +
            "bl\n" +
            "\n" +
            "vyrtk\n" +
            "hvaitkry\n" +
            "nyerqtvlkx\n" +
            "jrvytku\n" +
            "\n" +
            "wyjvfpqsxiotg\n" +
            "swjotvxqgy\n" +
            "sbcaotgrhqjvyexlw\n" +
            "toygjqxvwis\n" +
            "ytvxjwgqso\n" +
            "\n" +
            "b\n" +
            "jb\n" +
            "b\n" +
            "b\n" +
            "b\n" +
            "\n" +
            "hmoiwxluftbvyekj\n" +
            "fkvteiyojwbmlxh\n" +
            "ciqtkfvjgymenoxwldbp\n" +
            "\n" +
            "uvsfb\n" +
            "vf\n" +
            "gefdojtv\n" +
            "vfm\n" +
            "mfpv\n" +
            "\n" +
            "xrzvt\n" +
            "xtrv\n" +
            "hxtvr\n" +
            "vxrdbnt\n" +
            "rtxvz\n" +
            "\n" +
            "hctgpj\n" +
            "vctpeqgkrmloyhj\n" +
            "cpghzdtj\n" +
            "thcjgp\n" +
            "\n" +
            "oxd\n" +
            "xod\n" +
            "xod\n" +
            "xomdr\n" +
            "dxo\n" +
            "\n" +
            "no\n" +
            "a\n" +
            "\n" +
            "erjmoxdywnilqhtf\n" +
            "iuqjlmswzreoxfvphny\n" +
            "\n" +
            "gqlyohipcdnsmfvwjaxkbe\n" +
            "wsqholxbkaegijyvfmdpnc\n" +
            "laqkcdhpwgsvojeybmfinx\n" +
            "\n" +
            "mnec\n" +
            "mnc\n" +
            "cnm\n" +
            "mnc\n" +
            "\n" +
            "ympar\n" +
            "gcjhp\n" +
            "dqvxznwbueilkotfs\n" +
            "\n" +
            "retqbluxmovzcjpysia\n" +
            "xsqlpyfjmeztocunvirba\n" +
            "pozeqluyjscmibtarxv\n" +
            "\n" +
            "tj\n" +
            "htj\n" +
            "jt\n" +
            "tj\n" +
            "tj\n" +
            "\n" +
            "xhvictnm\n" +
            "kwpqvufoylb\n" +
            "\n" +
            "ksecubljnawx\n" +
            "uxnfkeljbrpsdz\n" +
            "\n" +
            "kcljaxwtopmqg\n" +
            "xktwagqponmjl\n" +
            "\n" +
            "bqemuordtawylnivpchx\n" +
            "cpwgotxmnjrbdliqaev\n" +
            "iqtwpacxebmlnsdrov\n" +
            "\n" +
            "ze\n" +
            "bhnrk\n" +
            "\n" +
            "quranol\n" +
            "roulaqvy\n" +
            "aulqroi\n" +
            "\n" +
            "btl\n" +
            "fbtu\n" +
            "dabkth\n" +
            "bts\n" +
            "\n" +
            "czq\n" +
            "cq\n" +
            "cq\n" +
            "qc\n" +
            "\n" +
            "rpwdmgqfxuhesynkl\n" +
            "jknhxtigcays\n" +
            "ghnyoixjazsk\n" +
            "\n" +
            "ovrhfpykmdctusixzlaew\n" +
            "hcodefmtvbgsxruqiwlpkjn\n" +
            "\n" +
            "w\n" +
            "w\n" +
            "w\n" +
            "\n" +
            "vbwxs\n" +
            "bxvws\n" +
            "mkbfwxsv\n" +
            "\n" +
            "rcksmaoz\n" +
            "lvu\n" +
            "pq\n" +
            "ht\n" +
            "\n" +
            "tzsvfeapbxlmcri\n" +
            "mbtplrfexvcszai\n" +
            "axmpszicltfvrbed\n" +
            "clamxvbezsprift\n" +
            "\n" +
            "kyglmxchpiw\n" +
            "ukcmpjwygxhli\n" +
            "wkygixhlczpm\n" +
            "\n" +
            "xvrcmntzgheu\n" +
            "dbjkwlpqcix\n" +
            "\n" +
            "rgmusakc\n" +
            "msgurca\n" +
            "uxgscaomkr\n" +
            "gjwfudczbrmtnas\n" +
            "magcusr\n" +
            "\n" +
            "rtlsbvnimh\n" +
            "bclehvunx\n" +
            "hqjvpyabdf\n" +
            "ovbhex\n" +
            "nhkbv\n" +
            "\n" +
            "achivfdsgwbmxjoez\n" +
            "fahrgmbnuqeztpvoc\n" +
            "\n" +
            "yjimzdhsbrtxocvkulanegfpwq\n" +
            "fwhkrjxpbqmvyiasduetncolgz\n" +
            "\n" +
            "oybpwzaumf\n" +
            "ypfoaedmzuxw\n" +
            "mawpfuzoy\n" +
            "wfapyoulzm\n" +
            "wmlyuafzoqp\n" +
            "\n" +
            "qamnfijrbzwduocvleyxshtpkg\n" +
            "udwjyghpmlqoczrbxfsekt\n" +
            "xrblgfoyedsmqwctzukpjh\n" +
            "\n" +
            "ctjumdkwfyvlrep\n" +
            "ckjqfwsauytzo\n" +
            "\n" +
            "vflnuezdymakghjs\n" +
            "dgczlrueyfkmqj\n" +
            "yjzkwgludmef\n" +
            "glfmjykiudez\n" +
            "zjobfutkpmydelrg\n" +
            "\n" +
            "ral\n" +
            "lgear\n" +
            "lra\n" +
            "lra\n" +
            "\n" +
            "ljytdae\n" +
            "ladujtef\n" +
            "jdptlaoxe\n" +
            "jdyaelt\n" +
            "\n" +
            "hwgkadmsnr\n" +
            "hrdakwgcsm\n" +
            "ramhslwdgk\n" +
            "yahlgscdmwkur\n" +
            "\n" +
            "spj\n" +
            "sj\n" +
            "jstc\n" +
            "\n" +
            "tpfjr\n" +
            "nyrfdlis\n" +
            "fjthr\n" +
            "\n" +
            "l\n" +
            "g\n" +
            "g\n" +
            "g\n" +
            "\n" +
            "awyvnf\n" +
            "vynaf\n" +
            "yavfn\n" +
            "nfavy\n" +
            "\n" +
            "jsycn\n" +
            "qsymphni\n" +
            "\n" +
            "wgnpjmtsvyh\n" +
            "wjgvspnyh\n" +
            "spjvgnywh\n" +
            "ygwnsvjph\n" +
            "\n" +
            "ghwey\n" +
            "zupo\n" +
            "bd\n" +
            "xvub\n" +
            "rmu\n" +
            "\n" +
            "ko\n" +
            "ok\n" +
            "ok\n" +
            "\n" +
            "xqchrioeazbkvdygtsl\n" +
            "ahqcdbgkvtzoeysxilr\n" +
            "\n" +
            "xjpykfoh\n" +
            "tfkcxopjh\n" +
            "\n" +
            "zslnekgdtvyxo\n" +
            "ovxzyedktfngws\n" +
            "ovtxyqednsrkzg\n" +
            "yvkdqsztogxne\n" +
            "lgesztknqcxdymuhov\n" +
            "\n" +
            "slhzwtiq\n" +
            "ziwhqtls\n" +
            "qzitsjxlwh\n" +
            "\n" +
            "typdxr\n" +
            "urxtpy\n" +
            "tyrxp\n" +
            "txyrp\n" +
            "xrypt\n" +
            "\n" +
            "oetyznfr\n" +
            "fntozyrx\n" +
            "hwaryotncfzvkj\n" +
            "inftzyor\n" +
            "\n" +
            "lmqxngr\n" +
            "zgrelxqa\n" +
            "pkjgvdqtyclforx\n" +
            "suiqrgxlb\n" +
            "hlwxbgrq\n" +
            "\n" +
            "pi\n" +
            "pci\n" +
            "thiyjpw\n" +
            "lmjpfti\n" +
            "pri\n" +
            "\n" +
            "cykj\n" +
            "cjlkg\n" +
            "zjvkc\n" +
            "\n" +
            "udihpjmfytbeskzv\n" +
            "zihutbpeysmvkjdf\n" +
            "kyhmpibtzuedfvsj\n" +
            "\n" +
            "upc\n" +
            "ud\n" +
            "otmuy\n" +
            "ul\n" +
            "\n" +
            "zlyfivurdqckmbjh\n" +
            "edmlbyjfvhuk\n" +
            "mlndjsagvfbwptxhy\n" +
            "\n" +
            "ryenbvawhdqpkmf\n" +
            "owkehyranzvbmdfqp\n" +
            "\n" +
            "pv\n" +
            "vp\n" +
            "pv\n" +
            "\n" +
            "yfuz\n" +
            "yzuf\n" +
            "zfuy\n" +
            "zfuy\n" +
            "fzyu\n" +
            "\n" +
            "abntu\n" +
            "nojuhst\n" +
            "tbfu\n" +
            "gvirxum\n" +
            "\n" +
            "owgmci\n" +
            "ycoxmagw\n" +
            "qmowhcv\n" +
            "\n" +
            "sgrmtfonvwlyi\n" +
            "wsyktlrnfihmv\n" +
            "lrftbaqwmnsyie\n" +
            "tpfylnrkwmis\n" +
            "nfowgyrilutms\n" +
            "\n" +
            "siw\n" +
            "stg\n" +
            "s\n" +
            "sg\n" +
            "\n" +
            "gswpatobqz\n" +
            "tqgdyzbopsaw\n" +
            "optaqszgfvwb\n" +
            "wzspagbotiqy\n" +
            "gpwbzstqoa\n" +
            "\n" +
            "hpmeifxjwlzsadrytuc\n" +
            "fjrhvyacxuwodpet\n" +
            "pxcwitdhfeuyraj\n" +
            "\n" +
            "nucleq\n" +
            "nqucel\n" +
            "uneqvcl\n" +
            "ceulnq\n" +
            "nlucqe\n" +
            "\n" +
            "hrz\n" +
            "qprg\n" +
            "rzxm\n" +
            "rj\n" +
            "\n" +
            "ltudnjkyxrae\n" +
            "ovljzxudgktr\n" +
            "kjilsumrdtxw\n" +
            "\n" +
            "mg\n" +
            "gm\n" +
            "mg\n" +
            "gm\n" +
            "mg\n" +
            "\n" +
            "vdrhzfaijp\n" +
            "ijprxvwt\n" +
            "rtpcixvj\n" +
            "\n" +
            "cudpsrbgjvtw\n" +
            "mwbtjpscudr\n" +
            "fpjywbontrzcs\n" +
            "bcwsijrpt\n" +
            "dctrwplbjs\n" +
            "\n" +
            "hgmjplf\n" +
            "hmlxgp\n" +
            "lgmpxh\n" +
            "\n" +
            "duyj\n" +
            "wjcmd\n" +
            "fapbqvjdh\n" +
            "\n" +
            "wrysjfdplgov\n" +
            "deznmktc\n" +
            "\n" +
            "jairuwz\n" +
            "juoaib\n" +
            "jkiouya\n" +
            "\n" +
            "yudqfn\n" +
            "zfqundy\n" +
            "uqdynf\n" +
            "qfdukyn\n" +
            "\n" +
            "vqwido\n" +
            "qviado\n" +
            "qdivo\n" +
            "kgodqvhi\n" +
            "\n" +
            "vrzysiwfmucdhnlxbtpe\n" +
            "nphxzelrmcyvituba\n" +
            "uebmctvxyjzlirphn\n" +
            "iqxobnuhrtckeyvpmlz\n" +
            "\n" +
            "mb\n" +
            "a\n" +
            "stzg\n" +
            "mp\n" +
            "mk\n" +
            "\n" +
            "pc\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "byacjmdq\n" +
            "dcbqymaj\n" +
            "\n" +
            "sbvfp\n" +
            "bxsoqpwuvide\n" +
            "\n" +
            "scjmloprtyexdaufhgn\n" +
            "qzthrdveixogscmbpfj\n" +
            "\n" +
            "ixlesvzjnrfwtpgqkabyd\n" +
            "zktsfxadvpbgwrnlyjq\n" +
            "jadfmrxvtgykpbznslqw\n" +
            "\n" +
            "wiscjd\n" +
            "qscjwid\n" +
            "swdcij\n" +
            "jwcdsi\n" +
            "siwjdc\n" +
            "\n" +
            "mafcigperqutny\n" +
            "rhtdceaxnijzlvq\n" +
            "xlsqckadbvnwetir\n" +
            "\n" +
            "ginltobkcuyvxdewmpa\n" +
            "gwbpmcytzvilkeujad\n" +
            "mqsyvgwdteiauclfbkp\n" +
            "\n" +
            "ryzscdbevj\n" +
            "wayrbivcmtnuo\n" +
            "gervcbyqjd\n" +
            "\n" +
            "uvdg\n" +
            "ugvqwmd\n" +
            "svugd\n" +
            "cgyhudfnv\n" +
            "vugd\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "oi\n" +
            "sid\n" +
            "\n" +
            "nyulf\n" +
            "unylf\n" +
            "lufyn\n" +
            "\n" +
            "mqsgtywlexjvib\n" +
            "tejyvxblgimwqs\n" +
            "bwtdeymxgslijkqvc\n" +
            "ygwtxqjvlsebmi\n" +
            "\n" +
            "zufj\n" +
            "zuf\n" +
            "\n" +
            "tf\n" +
            "v\n" +
            "ova\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "sxkcngriqjopeulybdfh\n" +
            "ykdgelruhxnpoicbqsjf\n" +
            "\n" +
            "fwypdk\n" +
            "yfwdk\n" +
            "\n" +
            "gqkp\n" +
            "qkpg\n" +
            "qpkg\n" +
            "qpgk\n" +
            "pgqk\n" +
            "\n" +
            "khfnscbly\n" +
            "zfhbclsynk\n" +
            "lkybcqsnh\n" +
            "lkbynhsc\n" +
            "hbskycln\n" +
            "\n" +
            "fevoigpcwtbzy\n" +
            "nleyjchafqkz\n" +
            "\n" +
            "reowqgsjyxn\n" +
            "tijopa\n" +
            "zajfholi\n" +
            "pzjodcal\n" +
            "\n" +
            "eujmvws\n" +
            "tzegmsiuj\n" +
            "hubnmwsjxe\n" +
            "\n" +
            "zotxy\n" +
            "ytox\n" +
            "yxto\n" +
            "toxny\n" +
            "yxot\n" +
            "\n" +
            "jnqzdpsmraikwfoghtxue\n" +
            "mthgnwpizudkraeqfsvx\n" +
            "zqxiasmpkrwegufnvydht\n" +
            "wraftbkmnilshugzedqxp\n" +
            "myfszgdxwnatupihrqek\n" +
            "\n" +
            "d\n" +
            "id\n" +
            "\n" +
            "vgit\n" +
            "tigv\n" +
            "tgvi\n" +
            "\n" +
            "yghsexuowr\n" +
            "hjwpfrn\n" +
            "nrdtazwfh\n" +
            "\n" +
            "ulzscyvhbedmkrpaoxjq\n" +
            "kfmlpzqwvuyrjntdabochi\n" +
            "kjldbrhzvmgyoaqepcu\n" +
            "\n" +
            "lbedykfihuwrqjga\n" +
            "tzdaycqijxvnofpms\n" +
            "\n" +
            "sjaxwn\n" +
            "asnxj\n" +
            "jasnx\n" +
            "xjsna\n" +
            "\n" +
            "ynuefovwlzkjrhtadqbcmpx\n" +
            "alsrtouvejnzkpghimq\n" +
            "sgjrzluknaetvmpqohi\n" +
            "\n" +
            "xptglvrwmnqeday\n" +
            "dgmwcevqraylntpx\n" +
            "awxgsypldervmqtz\n" +
            "\n" +
            "kxjcwuhgd\n" +
            "luikjwxna\n" +
            "\n" +
            "eypfmkhltigbqjr\n" +
            "lgqkyrhfjmpe\n" +
            "vlkpdyhenjzqg\n" +
            "\n" +
            "yhomsubzwtanxieglfcpr\n" +
            "tsmfaobhuwrxgclpizeyn\n" +
            "amyrsibwhfuelcgzoxpnt\n" +
            "\n" +
            "audfoqglzwbmxi\n" +
            "atezlmidbukqsxo\n" +
            "iubndahyxmvoqjrz\n" +
            "czstqouxbamdki\n" +
            "\n" +
            "vxcym\n" +
            "jxypngvm\n" +
            "\n" +
            "vcjqyfwarnpse\n" +
            "cznywqpraletsvuj\n" +
            "epknqavjywgcrs\n" +
            "\n" +
            "zcasgw\n" +
            "zhgwm\n" +
            "\n" +
            "q\n" +
            "j\n" +
            "gy\n" +
            "j\n" +
            "j\n" +
            "\n" +
            "x\n" +
            "y\n" +
            "x\n" +
            "\n" +
            "g\n" +
            "rg\n" +
            "g\n" +
            "g\n" +
            "\n" +
            "uqtbyxnprvsmoziw\n" +
            "hgrosbuwndt\n" +
            "sbgownrtdu\n" +
            "\n" +
            "tnmpvryj\n" +
            "boyvpjqinzrmct\n" +
            "rvyptmjn\n" +
            "nrmpytvj\n" +
            "hjpytrvnm\n" +
            "\n" +
            "tohzgmpsbd\n" +
            "agzhdstmbo\n" +
            "\n" +
            "rjoxmsunfz\n" +
            "dpualvqbhfwejo\n" +
            "xcyujfkrgo\n" +
            "\n" +
            "oknfcvwdehsyp\n" +
            "chdykwzeasovnfpt\n" +
            "opemfhcbdvsnywk\n" +
            "\n" +
            "bqksxvplr\n" +
            "jkyeqbczfwrl\n" +
            "ukqrlbo\n" +
            "\n" +
            "xmjfswhtepvilu\n" +
            "uvietwmjzlxfsh\n" +
            "mwfjsuotihlvexc\n" +
            "\n" +
            "rcmgbjyuwknhqfxazpi\n" +
            "rfixclqeagwpyukm\n" +
            "gowulqdpxracfysmki\n" +
            "furqvmasypwxckig\n" +
            "\n" +
            "qocmhepgrsadk\n" +
            "hotakpeqcgsnvmrdj\n" +
            "\n" +
            "hsadgzu\n" +
            "dakwghtlosfz\n" +
            "ipyjaqnxbvcm\n" +
            "\n" +
            "iyzxjgwpn\n" +
            "azgw\n" +
            "wzg\n" +
            "zwg\n" +
            "gwzt\n" +
            "\n" +
            "kd\n" +
            "kd\n" +
            "dk\n" +
            "dk\n" +
            "uwqdfbnrk\n" +
            "\n" +
            "qgevndtsowlmbpuyca\n" +
            "fsgrdkhcixbtqeyzju\n" +
            "\n" +
            "v\n" +
            "jbiq\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "bld\n" +
            "qd\n" +
            "d\n" +
            "\n" +
            "bupgemxrocniwhltyj\n" +
            "bnrhvefuqitwxpadjzg\n" +
            "\n" +
            "ulz\n" +
            "wkpnzsr\n" +
            "\n" +
            "du\n" +
            "jut\n" +
            "ujp\n" +
            "\n" +
            "vjomkthxbwezfaq\n" +
            "fqzhkovtejbwmxa\n" +
            "evfwkjxaqhbztmo\n" +
            "afojmbxehtsqzvwk\n" +
            "azxfhjqbokwvemt\n" +
            "\n" +
            "skbeotiuaqpfzvcr\n" +
            "fuaopcrzviesbtq\n" +
            "eqtsouizcvfapbr\n" +
            "tuzifcpqreoasbv\n" +
            "\n" +
            "vbaexcuwtzi\n" +
            "tvhabzwgux\n" +
            "etazxbvu\n" +
            "lakqvuxzbnto\n" +
            "\n" +
            "akmuwnefdzoi\n" +
            "lfbnetdxagwzcu\n" +
            "\n" +
            "cgut\n" +
            "cgt\n" +
            "gcut\n" +
            "tgc\n" +
            "tjcog\n" +
            "\n" +
            "meswxbkv\n" +
            "kxqdacuysmjeb\n" +
            "mbdsecryjkxa\n" +
            "\n" +
            "uczsvyqhn\n" +
            "zvshjyncxur\n" +
            "mchaunybvsz\n" +
            "nvhzyscu\n" +
            "vczyhnus\n" +
            "\n" +
            "rwufbi\n" +
            "iucbf\n" +
            "ifub\n" +
            "ibuf\n" +
            "ubfoi\n" +
            "\n" +
            "herxnv\n" +
            "hnxrev\n" +
            "hrevnx\n" +
            "nihverx\n" +
            "\n" +
            "oarje\n" +
            "eaojr\n" +
            "earjomt\n" +
            "ajiroe\n" +
            "eauokrj\n" +
            "\n" +
            "i\n" +
            "v\n" +
            "\n" +
            "hfizv\n" +
            "mzsigcojf\n" +
            "fzia\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "sduajrytgfeqipmclwvnhzox\n" +
            "pldgorsanitxuhzjqevwymcf\n" +
            "afpxlwzsimtcryhnujqdegov\n" +
            "scjtheoaynidugrvwzmqlpfx\n" +
            "\n" +
            "ubxzioenaqhvdfj\n" +
            "qbpxnwufaihevjyo\n" +
            "qznuhbfjovaxei\n" +
            "ibeuaovxqznfjh\n" +
            "\n" +
            "gvynpistahco\n" +
            "xaipcvthnoy\n" +
            "tiocvnakhyp\n" +
            "\n" +
            "jdz\n" +
            "mvrzdi\n" +
            "hbtzlodnyc\n" +
            "pdz\n" +
            "\n" +
            "z\n" +
            "ge\n" +
            "yonxvl\n" +
            "\n" +
            "ikuebtopyx\n" +
            "uxtbkiehpo\n" +
            "bidqkezluoxwt\n" +
            "\n" +
            "axiklvqhebtf\n" +
            "vfgxrhdi\n" +
            "\n" +
            "aicedpvysfhrw\n" +
            "wfdcsyehavrip\n" +
            "tvdicyrspfeahw\n" +
            "\n" +
            "ogdnu\n" +
            "ywpnlodb\n" +
            "hdnorw\n" +
            "\n" +
            "sclvgamkurpwzdbyqoien\n" +
            "wqgxeutjonpziklbma\n" +
            "lqinmbgekaowzup\n" +
            "webzlumakoigqnp\n" +
            "\n" +
            "s\n" +
            "b\n" +
            "b\n" +
            "b\n" +
            "\n" +
            "kiry\n" +
            "arm\n" +
            "sqtxclu\n" +
            "\n" +
            "qbkl\n" +
            "ekwjlfxq\n" +
            "qkl\n" +
            "lqkv\n" +
            "qklc\n" +
            "\n" +
            "ygzincjhtdlvxqwuosb\n" +
            "hngptjwzxislvcbdoyuq\n" +
            "\n" +
            "rvoxnejykzscfudtgi\n" +
            "jdkoentifrzvcygsux\n" +
            "kryitcznsdujogefxv\n" +
            "xiygudzeovsfnjtcrk\n" +
            "fknotuvcdexsygjzir\n" +
            "\n" +
            "xq\n" +
            "xt\n" +
            "x\n" +
            "\n" +
            "xdkrwqputigyajze\n" +
            "swnbfomjclvh\n" +
            "\n" +
            "w\n" +
            "lhrt\n" +
            "cj\n" +
            "u\n" +
            "nxcb\n" +
            "\n" +
            "qk\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "mjafwbpvoklt\n" +
            "ojavmbwplkf\n" +
            "blvaokmjwfp\n" +
            "ovjmdpbfwktla\n" +
            "kpalobujvfwm\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "\n" +
            "eva\n" +
            "qcv\n" +
            "rsloxgdwnmfi\n" +
            "zcb\n" +
            "\n" +
            "konzxcldaw\n" +
            "nzwsouarxlf\n" +
            "onqlzwbvxa\n" +
            "owaxqlzn\n" +
            "\n" +
            "vornwcbd\n" +
            "odeacqur\n" +
            "pcfkxshogt\n" +
            "\n" +
            "bzyiswgjaplqrmucnt\n" +
            "mrwqcdzytsgpaniljb\n" +
            "qpstmlrunbwcgyijaz\n" +
            "wtklbrsaicnjqpmgzy\n" +
            "\n" +
            "lixqjmvwscabofzgekhr\n" +
            "bewcrfvozxtjiqkaslmgh\n" +
            "fxvrgmlibozceqhjsawk\n" +
            "\n" +
            "dnzcarkvpwmbjqyit\n" +
            "bezpcaiyfkwnmtjrdq\n" +
            "bxjtqmakndwyrisczp\n" +
            "dpiymvtjzcbkqanlrwe\n" +
            "gdyctfvnmkjowqhprbazi\n" +
            "\n" +
            "fhr\n" +
            "hrf\n" +
            "yunrfh\n" +
            "rhf\n" +
            "\n" +
            "baehycmkjovgnpi\n" +
            "vnokepjcmbhiya\n" +
            "\n" +
            "xvltzoednwuq\n" +
            "bsnwprxvdulyzqeat\n" +
            "lijmhvnuzexdqwt\n" +
            "zjdlvtunwxeq\n" +
            "zmnlwxtuqevd\n" +
            "\n" +
            "rspkajy\n" +
            "pskra\n" +
            "fkepatrs\n" +
            "sprka\n" +
            "\n" +
            "ltvzbjgh\n" +
            "albhtjyvzk\n" +
            "zvjbtelh\n" +
            "lhjbvtzk\n" +
            "hdvtzlkjb\n" +
            "\n" +
            "czvmwjaghquxslrkteib\n" +
            "qxrahpukngbmwejzcsy\n" +
            "\n" +
            "xhfsuorb\n" +
            "volzamjey\n" +
            "\n" +
            "pgendrayv\n" +
            "urctvbdy\n" +
            "fpqndkvy\n" +
            "oidsvwh\n" +
            "gydvck\n" +
            "\n" +
            "wferdzc\n" +
            "cdfzewr\n" +
            "\n" +
            "a\n" +
            "lx\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "kncvymsgfa\n" +
            "cfqanuydkg\n" +
            "fktnycago\n" +
            "xgkerpcfyna\n" +
            "anwuhtfikgcy\n" +
            "\n" +
            "cpeh\n" +
            "dpqiksmzwr\n" +
            "\n" +
            "wbzokycijumplxrfhvnq\n" +
            "vqonfwreaidkxbhsp\n" +
            "\n" +
            "kmlnw\n" +
            "klmn\n" +
            "mklng\n" +
            "lknmg\n" +
            "\n" +
            "ojbykxcefdshgrwimtqp\n" +
            "gmqedbfxpwntkrcjho\n" +
            "tkexprjngfwdmcohqb\n" +
            "mepqwjrxkbgdtcfho\n" +
            "\n" +
            "avtklxnmujiwr\n" +
            "tknaprujwiv\n" +
            "aywvgfnitrck\n" +
            "\n" +
            "nizxaebqrkcwvjut\n" +
            "mrgodaztnipsjbxlq\n" +
            "rhbqntaiuxzj\n" +
            "\n" +
            "kfjwgmlyr\n" +
            "notbhxdicavqs\n" +
            "\n" +
            "vaqidgkolexjcnbys\n" +
            "itwlxyesqocjprdunb\n" +
            "ncoyelzfsmbhqxji\n" +
            "\n" +
            "w\n" +
            "q\n" +
            "\n" +
            "myhultgvxew\n" +
            "obcsfrklqaxpij\n" +
            "\n" +
            "tujq\n" +
            "uqztxbj\n" +
            "ajgumtqlvsewrc\n" +
            "tqjnou\n" +
            "\n" +
            "wvlxdsajnc\n" +
            "ajvrwhkspn\n" +
            "\n" +
            "gz\n" +
            "gez\n" +
            "ze\n" +
            "yxz\n" +
            "\n" +
            "luyj\n" +
            "ljduny\n" +
            "ljyu\n" +
            "yjul\n" +
            "juyl\n" +
            "\n" +
            "gbpfexukwdljnvaromisqhc\n" +
            "ezsaumkfvxpnchdtlborqjwgi\n" +
            "\n" +
            "gzklpuaqehvio\n" +
            "sijxncbmwfy\n" +
            "\n" +
            "vkwnrcyth\n" +
            "vectwfk\n" +
            "\n" +
            "sg\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "az\n" +
            "caz\n" +
            "zfta\n" +
            "caz\n" +
            "\n" +
            "jlrifchmk\n" +
            "irkjhmcfl\n" +
            "ifqmpklchjrb\n" +
            "kcjmlfhri\n" +
            "ilmkhfcjr\n" +
            "\n" +
            "tjnqf\n" +
            "ncyzf\n" +
            "f\n" +
            "fo\n" +
            "lxdrgsfihbew\n" +
            "\n" +
            "ntirwquhv\n" +
            "qwvhyuintr\n" +
            "\n" +
            "gvunymbitk\n" +
            "dsbywnmzk\n" +
            "qjanlhbxmroc\n" +
            "\n" +
            "pxsdylnmfhq\n" +
            "pyduhnqmfxl\n" +
            "dpmqchxtnlbyf\n" +
            "hnpqlxydfm\n";

    public static void main(String[] args) {
        List<String> groups = Arrays.asList(INPUT.split("\n\n").clone());
        int sum = 0;
        for (String group : groups) {
            List<Set<String>> sets = new ArrayList<>();
            for (String person : group.split("\n")) {
                Set<String> chSet = new HashSet<>();
                for (int i = 0; i < person.length(); i++) {
                    char c = person.charAt(i);
                    String ch = Character.toString(c);
                    if (StringUtils.isNotBlank(ch)) {
                        chSet.add(ch);
                    }
                }
                sets.add(chSet);
            }
            Set<String> firstSet = sets.get(0);
            for (int i = 1; i < sets.size(); i++) {
                firstSet.retainAll(sets.get(i));
            }
            sum += firstSet.size();
        }
        System.out.println(sum);
    }
}
